Regen after previous change.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1626,6 +1626,7 @@ Optional Features:
                              loongson2e: 64-bit Loongson-2E vector backend
                              loongson2f: 64-bit Loongson-2F vector backend
                              neon: 64-bit ARM NEON vector backend
+                             vis: 64-bit SPARC VIS 1 vector backend
   --enable-tune-cache[=yes]
                           Use the pre-tuned cached configuration if it exists.
                              It has no effect if --enable-backend=none.
@@ -4571,13 +4572,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4574: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4575: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4577: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4578: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4580: output\"" >&5)
+  (eval echo "\"\$as_me:4581: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5783,7 +5784,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5786 "configure"' > conftest.$ac_ext
+  echo '#line 5787 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7638,11 +7639,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7641: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7642: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7645: \$? = $ac_status" >&5
+   echo "$as_me:7646: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7977,11 +7978,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7980: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7981: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7984: \$? = $ac_status" >&5
+   echo "$as_me:7985: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8082,11 +8083,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8085: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8086: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8089: \$? = $ac_status" >&5
+   echo "$as_me:8090: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8137,11 +8138,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8140: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8141: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8144: \$? = $ac_status" >&5
+   echo "$as_me:8145: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10940,7 +10941,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10943 "configure"
+#line 10944 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11036,7 +11037,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11039 "configure"
+#line 11040 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13944,6 +13945,63 @@ if test $ac_cv_defined___ARM_NEON__ != "no"; then
   OPT_BACKEND=neon
 fi
 
+# For SPARC VIS and GCC, there are no macros or headers and we
+# can't induce VIS from other macros as it's not "standard SPARC".
+# To see if VIS is on by default, we have to try to compile
+# something that'll fail if a VIS-specific builtin isn't defined.
+# Even then, don't enable it; it fails silently on e.g. Niagara T1.
+if test ${rapp_tune_generation} = no; then
+    { $as_echo "$as_me:$LINENO: checking for intrinsics support for VIS" >&5
+$as_echo_n "checking for intrinsics support for VIS... " >&6; }
+    have_vis=no
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+typedef unsigned char v8qi __attribute__((__vector_size__(8)));
+           v8qi x,y,z;
+           void f(void){x=__builtin_vis_faligndatav8qi(y,z);}
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  # Adjust text and prepend "OPT_BACKEND=vis; " to enable by default.
+      have_vis="yes, configure with --enable-backend=vis to enable"
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext;
+    { $as_echo "$as_me:$LINENO: result: $have_vis" >&5
+$as_echo "$have_vis" >&6; }
+fi
 
 { $as_echo "$as_me:$LINENO: checking for __SSE2__ defined" >&5
 $as_echo_n "checking for __SSE2__ defined... " >&6; }
@@ -14339,7 +14397,7 @@ if test "${enable_backend+set}" = set; then
        OPT_BACKEND=
        PLATFORM=generic
        ;;
-   mmx | sse | sse2 | ssse3 | altivec | vadmx)
+   mmx | sse | sse2 | ssse3 | altivec | vadmx | vis)
        OPT_BACKEND=${enableval}
        AM_CFLAGS="${AM_CFLAGS} -m${OPT_BACKEND}"
        ;;
@@ -14474,6 +14532,19 @@ _ACEOF
           { $as_echo "$as_me:$LINENO: result: $initializer" >&5
 $as_echo "$initializer" >&6; }
           ;;
+   vis)
+          backend_info_name="VIS 1"
+
+          # Need to provide a macro to show explicitly when we
+          # want to use this support, as there is no indicator
+          # other than that the code compiles.
+
+cat >>confdefs.h <<_ACEOF
+#define RC_VEC_BACKEND_VIS 1
+_ACEOF
+
+          ;;
+
    loongson2ef)
           backend_info_name="Loongson-2E and -2F"
           ;;
